import Head from "next/head";
import { Inter } from "@next/font/google";

import Header from "@/components/Header";
import Banner from "@/components/Banner";
import SmallCard from "@/components/SmallCard";
import MediumCard from "@/components/MediumCard";
import LargeCard from "@/components/LargeCard";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
	return (
		<>
			<Head>
				<title>Airbnb clone</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link
					rel="shortcut icon"
					sizes="76x76"
					type="image/x-icon"
					href="https://a0.muscache.com/airbnb/static/logotype_favicon-21cc8e6c6a2cca43f061d2dcabdf6e58.ico"
				/>
				<link
					rel="stylesheet"
					href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
					integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
					crossorigin=""
				/>
				<script
					src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
					integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM="
					crossorigin=""
				></script>
			</Head>
			<Header />
			<Banner />
			<main className="px-8 mx-auto max-w-7xl sm:px-16">
				<section className="pt-6">
					<h2 className="text-4xl font-semibold pd-5">Explore Nearby</h2>

					<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
						{props.exploreData?.map((item) => (
							<SmallCard
								key={item.img}
								img={item.img}
								location={item.location}
								distance={item.distance}
							/>
						))}
					</div>
				</section>
				<section>
					<h2 className="py-8 text-4xl font-semibold">Live Anywhere</h2>
					<div className="flex space-x-3 overflow-x-scroll overflow-y-hidden ">
						{props.cardsData?.map(({ img, title }) => (
							<MediumCard key={img} img={img} title={title} />
						))}
					</div>
				</section>

				<LargeCard
					img="https://links.papareact.com/4cj"
					title="The Greatest Outdoors"
					description="Wishlists curated by Airbnb"
					buttonText="Get Inspired"
				/>
			</main>
			<Footer />
		</>
	);
}

export async function getStaticProps() {
	const exploreData = [
		{
			img: "https://links.papareact.com/5j2",
			location: "London",
			distance: "45-minute drive",
		},
		{
			img: "https://links.papareact.com/1to",
			location: "Manchester",
			distance: "4.5-hour drive",
		},
		{
			img: "https://links.papareact.com/40m",
			location: "Liverpool",
			distance: "4.5-hour drive",
		},
		{
			img: "https://links.papareact.com/msp",
			location: "York",
			distance: "4-hour drive",
		},
		{
			img: "https://links.papareact.com/2k3",
			location: "Cardiff",
			distance: "45-minute drive",
		},
		{
			img: "https://links.papareact.com/ynx",
			location: "Birkenhead",
			distance: "4.5-hour drive",
		},
		{
			img: "https://links.papareact.com/kji",
			location: "Newquay",
			distance: "6-hour drive",
		},
		{
			img: "https://links.papareact.com/41m",
			location: "Hove",
			distance: "2-hour drive",
		},
	];
	const cardsData = [
		{ img: "https://links.papareact.com/2io", title: "Outdoor getaways" },
		{ img: "https://links.papareact.com/q7j", title: "Unique stays" },
		{ img: "https://links.papareact.com/s03", title: "Entire homes" },
		{ img: "https://links.papareact.com/8ix", title: "Pet allowed" },
		{ img: "https://links.papareact.com/2io", title: "Outdoor getaways" },
		{ img: "https://links.papareact.com/q7j", title: "Unique stays" },
		{ img: "https://links.papareact.com/s03", title: "Entire homes" },
		{ img: "https://links.papareact.com/8ix", title: "Pet allowed" },
	];

	return {
		props: {
			exploreData,
			cardsData,
		},
	};
}
